services:
  target:
    build: ./target
    container_name: vuln-target
    expose:
      - "8080"
    ports:
      - "8080:8080"

  attacker:
    build: ./attacker
    container_name: vuln-attacker
    tty: true
    depends_on:
      - target
